name: build

permissions:
  contents: read

on:
  push:
    branches: '**'
    paths:
      - 'src/**' # React to source files changing

  workflow_dispatch: # Allow manual runs

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    uses: Owl-Domain/.github/.github/workflows/dotnet_build.yml@main
    with:
      configuration: ${{ matrix.configuration }}
